/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : W:\gbdk\02-04-backgrounds\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MAPWidth 40
#define MAPHeight 18
#define MAPBank 0

extern unsigned char MAP[];

/* End of MAP.H */
